### ISSUE TITLE
View User Profile Details

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-fakes-news#28]
As an author, I would like to see the content of a User Profile so I can read it.

**Given** a user is viewing a list of User Profiles  
**When** they select a user
**Then** they should be directed to a User Profile Detail page

User Profile Details include:

* Full name
* Avatar image (if exists, else use a default image)
* Display name
* Email
* Creation Date (MM/DD/YYYY)

**Comment by justha** [comment]
Routes user to MyProfile page from NavBar link. 
Does not properly display user profile properties yet.

**Comment by justha** [comment]
Fixed fetch URL. MyProfile now displays all user details, except...
- Full Name (pending ticket #59)
- Profile Type (pending ticket #59)
- Avatar Image

**Comment by justha** [comment]
User image displays. Ready for testing.

**Comment by justha** [comment]
Ticket #59 complete. 
Registration localStorage method was also updated to display user detail on registration. 
All user details and avatar properly display upon registration and login now.
